### ISSUE TITLE
All moves show as Illegal?

### ISSUE THREAD

**Issue by alchzh** [sdgu/collab-teambuilder#1]
![screenshot 2016-04-07 at 7 59 45 am](https://cloud.githubusercontent.com/assets/8976828/14350335/ba95f1f2-fc96-11e5-9790-b3f3addf40a4.png)  
As you can see above, it seems that all moves (discounting Hidden Power) show up as "Illegal" in the move suggestion. This doesn't change much but still odd...

**Comment by shshsh11** [comment]
Should be fixed now. It was having an issue with Pokemon that didn't have two prevos because I wasn't careful in my checking.
